// Core WebVTT options (existing Video.js API)
export interface TextTrackOptions {
  kind?: 'subtitles' | 'captions';
  src?: string;
  srclang?: string;
  label?: string;
  default?: boolean;
  maxWords?: number;
  wordHighlight?: boolean;
}

export interface AutoGeneratedTextTrackOptions {
  autoGenerateSubtitles: true;
  default?: boolean;
  translate?: Array<{ langCode: string; label?: string; default?: boolean }>;
  maxWords?: number;
  wordHighlight?: boolean;
};

export type RemoteTextTrackOptions  = TextTrackOptions | AutoGeneratedTextTrackOptions 