/**
 * Core WebVTT options for text tracks (subtitles/captions).
 * Used for regular text tracks with a source URL.
 */
export interface TextTrackOptions {
  /**
   * The kind of text track: 'subtitles' or 'captions'
   */
  kind?: 'subtitles' | 'captions';
  /**
   * The URL of the subtitle/caption file (VTT, SRT, etc.)
   * For transcript files, use a URL ending with '.transcript'
   */
  src?: string;
  /**
   * Language code for the text track (e.g., 'en', 'es', 'fr')
   */
  srclang?: string;
  /**
   * Display label for the text track in the subtitle menu
   */
  label?: string;
  /**
   * Whether this track should be selected by default
   */
  default?: boolean;
  /**
   * Maximum number of characters that can appear on a subtitle frame (only for transcript files)
   * @default 60
   */
  maxChars?: number;
  /**
   * Enable word-level highlighting in subtitles (only for transcript files)
   * When enabled, words are highlighted as they are spoken
   * @default false
   */
  highlightWords?: boolean;
}

export const languageCodes = Object.freeze({
  en: "English",
  es: "Spanish",
  fr: "French",
  de: "German",
  it: "Italian",
  pt: "Portuguese",
  nl: "Dutch",
  hi: "Hindi",
  ja: "Japanese",
  zh: "Chinese",
  fi: "Finnish",
  ko: "Korean",
  pl: "Polish",
  ru: "Russian",
  tr: "Turkish",
  uk: "Ukrainian",
  vi: "Vietnamese",
  af: "Afrikaans",
  sq: "Albanian",
  am: "Amharic",
  ar: "Arabic",
  hy: "Armenian",
  as: "Assamese",
  az: "Azerbaijani",
  ba: "Bashkir",
  eu: "Basque",
  be: "Belarusian",
  bn: "Bengali",
  bs: "Bosnian",
  br: "Breton",
  bg: "Bulgarian",
  my: "Burmese",
  ca: "Catalan",
  hr: "Croatian",
  cs: "Czech",
  da: "Danish",
  et: "Estonian",
  fo: "Faroese",
  gl: "Galician",
  ka: "Georgian",
  el: "Greek",
  gu: "Gujarati",
  ht: "Haitian",
  ha: "Hausa",
  haw: "Hawaiian",
  he: "Hebrew",
  hu: "Hungarian",
  is: "Icelandic",
  id: "Indonesian",
  jw: "Javanese",
  kn: "Kannada",
  kk: "Kazakh",
  km: "Khmer",
  lo: "Lao",
  la: "Latin",
  lv: "Latvian",
  ln: "Lingala",
  lt: "Lithuanian",
  lb: "Luxembourgish",
  mk: "Macedonian",
  mg: "Malagasy",
  ms: "Malay",
  ml: "Malayalam",
  mt: "Maltese",
  mi: "Maori",
  mr: "Marathi",
  mn: "Mongolian",
  ne: "Nepali",
  no: "Norwegian",
  nn: "Norwegian Nynorsk",
  oc: "Occitan",
  pa: "Panjabi",
  ps: "Pashto",
  fa: "Persian",
  ro: "Romanian",
  sa: "Sanskrit",
  sr: "Serbian",
  sn: "Shona",
  sd: "Sindhi",
  si: "Sinhala",
  sk: "Slovak",
  sl: "Slovenian",
  so: "Somali",
  su: "Sundanese",
  sw: "Swahili",
  sv: "Swedish",
  tl: "Tagalog",
  tg: "Tajik",
  ta: "Tamil",
  tt: "Tatar",
  te: "Telugu",
  th: "Thai",
  bo: "Tibetan",
  tk: "Turkmen",
  ur: "Urdu",
  uz: "Uzbek",
  cy: "Welsh",
  yi: "Yiddish",
  yo: "Yoruba",
});

/**
 * Options for auto-generated subtitles using AI transcription.
 * When autoGenerate is true, subtitles are automatically generated from the video's audio.
 */
export interface AutoGeneratedTextTrackOptions {
  /**
   * Must be set to true to enable auto-generated subtitles
   */
  autoGenerate: true;
  /**
   * Whether to show auto-generated subtitles in the subtitle dropdown menu
   * @default true
   */
  showAutoGenerated?: boolean;
  /**
   * Maximum number of characters that can appear on a subtitle frame
   * @default 60
   */
  maxChars?: number;
  /**
   * Enable word-level highlighting in subtitles
   * When enabled, words are highlighted as they are spoken
   * @default false
   */
  highlightWords?: boolean;
  /**
   * Custom label for the auto-generated subtitle track
   * If not provided, defaults to "AI Gen Subtitles"
   */
  autoGeneratedLabel?: string;
  /**
   * Whether this track should be selected by default
   */
  default?: boolean;
  /**
   * Array of translation options for the auto-generated subtitles
   * Each translation provides subtitles in a different language
   */
  translations?: Array<{
    /**
     * Language code for the translation (e.g., 'fr', 'hi', 'es')
     * Must be a valid key from the languageCodes object
     */
    langCode: keyof typeof languageCodes;
    /**
     * Custom label for this translation track
     * If not provided, defaults to "{Language Name} (AI generated)"
     */
  label?: string;
    /**
     * Whether this translation should be selected by default
     */
    default?: boolean;
  }>;
}

export type RemoteTextTrackOptions = TextTrackOptions | AutoGeneratedTextTrackOptions;