import { videoPlayer } from '@imagekit/video-player';
import '@imagekit/video-player/styles.css';
import { buildPlayerInitCode, formatObjectAsCode } from './codegen';

// --- Actual Player Initialization (single source of truth) ---
const playerOptions = {
  imagekitId: 'zuqlyov9d', // Replace with your ImageKit ID
  logo: {
    showLogo: true,
    logoImageUrl: 'https://imagekit.io/icons/icon-144x144.png',
    logoOnclickUrl: 'https://imagekit.io/',
  },
};

const videoJsOptions = {
  muted: true,
};

const srcConfig = {
  src: 'https://stage-ik.imagekit.io/a8fli6vdg/New%20Folder33/JackMa_RuBbxVpuX.mp4?updatedAt=1762764326271&version=yashtest3&ik=debug=true',
  textTracks: [
    {
      autoGenerate: true,
      maxWordsPerLine: 4,
      highlightWords: true,
    },
    {
      autoGenerate: true,
      showAutoGenerated: false,
      translations: [
        {
          langCode: 'hi',
          label: 'Hindi (AI)',
          default: true,
        },
        {
          langCode: 'de',
          label: 'German (AI)',
        },
      ],
    },
  ],
};

// Generated code always matches the real config above
const codeToDisplay = buildPlayerInitCode({
  htmlHint: '<video id="player" class="video-js" ...></video>',
  playerTarget: 'player',
  playerOptions,
  videoJsOptions,
  afterInitLines: [``, `player.src(${formatObjectAsCode(srcConfig)});`],
});

document.getElementById('code-display')!.textContent = codeToDisplay.trim();

const player = videoPlayer('player', playerOptions, videoJsOptions);
player.src(srcConfig);