import { videoPlayer, languageCodes } from '@imagekit/video-player';
import '@imagekit/video-player/dist/styles.css';
import type { 
    IKPlayerOptions, 
    SourceOptions, 
    RemoteTextTrackOptions,
    AutoGeneratedTextTrackOptions 
} from '@imagekit/video-player';
import type Player from 'video.js/dist/types/player';

let currentPlayer: Player | null = null;

/**
 * Formats a JavaScript object/array/value as a code string with proper indentation
 * Uses JSON.stringify with a replacer to handle undefined, then converts to JS format
 */
function formatObjectAsCode(value: any): string {
    // Custom replacer to handle undefined (JSON.stringify normally skips it)
    const replacer = (key: string, val: any) => {
        if (val === undefined) {
            return '__UNDEFINED__'; // Placeholder we'll replace later
        }
        return val;
    };

    // Use JSON.stringify with 4-space indentation
    let jsonString = JSON.stringify(value, replacer, 4);
    
    // Convert JSON format to JavaScript format:
    // 1. Remove quotes from valid JavaScript identifier keys
    // 2. Replace double quotes with single quotes for string values
    // 3. Replace undefined placeholder
    
    // Step 1: Remove quotes from valid identifier keys and convert to single quotes for invalid ones
    jsonString = jsonString.replace(/"([^"]+)":/g, (_match, key) => {
        const isValidIdentifier = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);
        if (isValidIdentifier) {
            return `${key}:`; // Remove quotes from valid identifiers
        }
        return `'${key}':`; // Use single quotes for invalid identifiers
    });
    
    // Step 2: Replace double quotes in string values with single quotes
    // We need to be careful - only replace quotes that are part of string values
    // After keys are handled, remaining " should be string values
    jsonString = jsonString.replace(/"/g, "'");
    
    // Step 3: Replace undefined placeholder (but only when it's a value, not part of a string)
    jsonString = jsonString.replace(/__UNDEFINED__/g, 'undefined');
    
    return jsonString;
}

/**
 * Builds the player configuration objects based on form inputs
 */
function buildPlayerConfig(
    imagekitId: string,
    srcUrl: string,
    features: string[],
    maxWords?: number,
    wordHighlight?: boolean,
    translationLangs?: string[]
): { playerOptions: IKPlayerOptions; srcConfig: SourceOptions } {
    // Build player options
    const playerOptions: IKPlayerOptions = {
        imagekitId: imagekitId,
    };

    if (features.includes('seek-thumbnails')) {
        playerOptions.seekThumbnails = true;
    }

    // Build source config
    const srcConfig: SourceOptions = {
        src: srcUrl,
    };

    if (features.includes('chapters')) {
        srcConfig.chapters = true;
    }

    // Build text tracks
    if (features.includes('subtitles') || features.includes('translation')) {
        const textTracks: RemoteTextTrackOptions[] = [];

        // Add subtitles track if subtitles is checked
        if (features.includes('subtitles')) {
            const subtitleConfig: AutoGeneratedTextTrackOptions = {
                autoGenerateSubtitles: true,
            };

            if (maxWords !== undefined && maxWords > 0) {
                subtitleConfig.maxWords = maxWords;
            }
            if (wordHighlight) {
                subtitleConfig.wordHighlight = true;
            }

            textTracks.push(subtitleConfig);
        }

        // Add translation track as a separate track if translation is checked
        if (features.includes('translation')) {
            const translateArray: Array<{ langCode: keyof typeof languageCodes; label?: string; default?: boolean }> = [];
            if (translationLangs && translationLangs.length > 0) {
                translationLangs.forEach(lang => {
                    translateArray.push({
                        langCode: lang.trim() as keyof typeof languageCodes,
                        label: `${getLanguageName(lang.trim())} (AI)`,
                    });
                });
            } else {
                // Default languages if none specified
                translateArray.push({
                    langCode: 'fr' as const,
                    label: 'French (AI)',
                });
                translateArray.push({
                    langCode: 'de' as const,
                    label: 'German (AI)',
                });
            }

            const translationConfig: AutoGeneratedTextTrackOptions = {
                autoGenerateSubtitles: true,
                translate: translateArray,
            };

            textTracks.push(translationConfig);
        }

        if (textTracks.length > 0) {
            srcConfig.textTracks = textTracks;
        }
    }

    return { playerOptions, srcConfig };
}

/**
 * Generates code string from configuration objects
 */
function generateCode(
    imagekitId: string,
    srcUrl: string,
    features: string[],
    maxWords?: number,
    wordHighlight?: boolean,
    translationLangs?: string[]
): string {
    const { playerOptions, srcConfig } = buildPlayerConfig(
        imagekitId,
        srcUrl,
        features,
        maxWords,
        wordHighlight,
        translationLangs
    );

    const playerOptionsCode = formatObjectAsCode(playerOptions);
    const srcConfigCode = formatObjectAsCode(srcConfig);

    return `// HTML: <video id="player" class="video-js" ...></video>

import { videoPlayer } from '@imagekit/video-player';
import '@imagekit/video-player/dist/styles.css';

const player = videoPlayer('player', ${playerOptionsCode}, {
    muted: true
});

player.src(${srcConfigCode});`;
}

function getLanguageName(langCode: string): string {
    const langNames: { [key: string]: string } = {
        'fr': 'French',
        'de': 'German',
        'hi': 'Hindi',
        'es': 'Spanish',
        'it': 'Italian',
        'pt': 'Portuguese',
        'ru': 'Russian',
        'ja': 'Japanese',
        'ko': 'Korean',
        'zh': 'Chinese',
        'ar': 'Arabic',
        'nl': 'Dutch',
        'pl': 'Polish',
        'tr': 'Turkish',
    };
    return langNames[langCode.toLowerCase()] || langCode.toUpperCase();
}

function updatePlayer() {
    const imagekitId = (document.getElementById('imagekit-id') as HTMLInputElement).value.trim();
    const srcUrl = (document.getElementById('src-url') as HTMLInputElement).value.trim();
    const checkboxes = document.querySelectorAll<HTMLInputElement>('input[name="features"]:checked');
    const features = Array.from(checkboxes).map(cb => cb.value);

    if (!imagekitId || !srcUrl) {
        alert('Please fill in both ImageKit ID and Source URL');
        return;
    }

    // Get subtitle options
    const maxWordsInput = document.getElementById('max-words') as HTMLInputElement;
    const maxWords = maxWordsInput?.value ? parseInt(maxWordsInput.value, 10) : undefined;
    const wordHighlight = (document.getElementById('word-highlight') as HTMLInputElement)?.checked || false;

    // Get translation language codes
    const translationLangsInput = document.getElementById('translation-langs') as HTMLInputElement;
    const translationLangsStr = translationLangsInput?.value.trim() || '';
    const translationLangs = translationLangsStr ? translationLangsStr.split(',').map(l => l.trim()).filter(l => l.length > 0) : undefined;

    // Build configuration using shared function
    const { playerOptions, srcConfig } = buildPlayerConfig(
        imagekitId,
        srcUrl,
        features,
        maxWords,
        wordHighlight,
        translationLangs
    );

    // Generate and display code
    const code = generateCode(imagekitId, srcUrl, features, maxWords, wordHighlight, translationLangs);
    document.getElementById('code-display')!.textContent = code;

    // Get the video element before disposing
    let videoElement = document.getElementById('player') as HTMLVideoElement;
    
    // Destroy existing player if it exists
    if (currentPlayer) {
        try {
            currentPlayer.dispose();
            currentPlayer = null;
        } catch (e) {
            // Player might already be disposed
            currentPlayer = null;
        }
    }

    // Ensure the video element still exists, recreate if needed
    if (!videoElement || !videoElement.parentNode) {
        const playerContainer = document.querySelector('.player-container');
        if (playerContainer) {
            playerContainer.innerHTML = '<video id="player" class="video-js" controls preload="auto" width="960" height="540"></video>';
            videoElement = document.getElementById('player') as HTMLVideoElement;
        } else {
            console.error('Player container not found');
            return;
        }
    }

    // Initialize new player using the element directly
    currentPlayer = videoPlayer(videoElement, playerOptions, {
        muted: true
    });

    // Set source with the configured options
    currentPlayer.src(srcConfig);
}

// Initial code display
const initialCode = generateCode(
    'zuqlyov9d',
    'https://stage-ik.imagekit.io/a8fli6vdg/New%20Folder33/JackMa_RuBbxVpuX.mp4?updatedAt=1762764326271&version=yashtest3&ik=debug=true',
    []
);
document.getElementById('code-display')!.textContent = initialCode;

// Initialize player with default values
const initialVideoElement = document.getElementById('player') as HTMLVideoElement;
if (initialVideoElement) {
    currentPlayer = videoPlayer(initialVideoElement, {
        imagekitId: 'zuqlyov9d',
    }, {
        muted: true
    });

    currentPlayer.src({
        src: 'https://stage-ik.imagekit.io/a8fli6vdg/New%20Folder33/JackMa_RuBbxVpuX.mp4?updatedAt=1762764326271&version=yashtest3&ik=debug=true',
    });
}

// Handle form submission
document.getElementById('player-form')!.addEventListener('submit', (e) => {
    e.preventDefault();
    updatePlayer();
});

