// modules/subtitles/subtitles.ts
import videojs from 'video.js';
import type Player from 'video.js/dist/types/player';
import type HTMLTrackElement from 'video.js/dist/types/tracks/html-track-element.d.ts';
import { languageCodes } from '../../interfaces';
import type { AutoGeneratedTextTrackOptions, IKPlayerOptions, RemoteTextTrackOptions, SourceOptions, TextTrackOptions } from '../../interfaces';
// import { Parser } from 'vtt.js'; // Import Parser from vtt.js


declare module 'video.js' {
    interface HtmlTrackElement {
        // Video.js exposes trackEl.track as a TextTrack
        track: TextTrack;
    }
}


// declare global {
//     interface Window {
//         WebVTT: {
//             Parser: typeof Parser;         // you can import Parser’s type from vtt.js if available
//             StringDecoder: () => any;
//         };
//     }
// }


// Word‐level transcript entry
interface WordTiming {
    word: string;
    start: number;
    end: number;
}

// Full transcript JSON entry
interface TranscriptEntry {
    transcript: string;
    confidence: number;
    words: WordTiming[];
    language?: string;
}

// Exported for testing purposes
export const log = videojs.log.createLogger('videojs-playlist');

// Setup subtitles: fetch or parse, build VTTCues, optional highlighting
async function setupSubtitles(params: {
    player: Player;
    opts: RemoteTextTrackOptions;
    currentSource?: SourceOptions;
    signerFn?: (src: string) => Promise<string> | undefined;
}): Promise<TextTrackOptions[]> {
    let { player, opts, currentSource, signerFn } = params;
    const { maxWords = 4, wordHighlight } = opts;

    let srcUrls: Array<string> = [];
    // if transcript url is provided
    if (hasSrc(opts)) {
        // If signerFn is provided, sign the URL
        if (signerFn) {
            const signedUrl = await signerFn(opts.src);
            srcUrls.push(signedUrl);
        }
    }
    else {
        // 1) Build translation URLs
        srcUrls = await prepareSubtitleSrc(
            opts,
            currentSource,
            signerFn,
        );
    }

    // console.log('Subtitles source URLs:', srcUrls);

    // artifical delay to simulate loading
    // await new Promise(resolve => setTimeout(resolve, 10000));



    // 1️. Fetch the transcript JSON
    const raw = await fetch(srcUrls[0]!).then(r => {
        if (!r.ok) throw new Error('Failed to fetch transcript');
        return r.text();
    });
    
    // Parse the JSON - now it has a root object with transcript array and languageCode
    const transcriptData = JSON.parse(raw) as {
        languageCode: string;
        transcript: Array<{
            transcript: string;
            confidence: number;
            words: Array<{
                word: string;
                start: number;
                end: number;
            }>;
        }>;
        paragraphs?: Array<{
            text: string;
            start: number;
            end: number;
            confidence: number;
        }>;
    };
    
    const entries = transcriptData.transcript;

    // 2. Flatten into word list
    // @ts-ignore
    const allWords = entries.flatMap(e => e.words);

    // 3. Build WebVTT string
    let vtt = 'WEBVTT\n\n';

    const fmt = (sec: number) => {
        const ms = Math.floor((sec % 1) * 1000).toString().padStart(3, '0');
        const s = Math.floor(sec % 60).toString().padStart(2, '0');
        const m = Math.floor((sec / 60) % 60).toString().padStart(2, '0');
        const h = Math.floor(sec / 3600).toString().padStart(2, '0');
        return `${h}:${m}:${s}.${ms}`;
    };

    for (let i = 0; i < allWords.length; i += maxWords) {
        const block = allWords.slice(i, i + maxWords);
        const start = fmt(block[0].start);
        const end = fmt(block[block.length - 1].end);

        // Wrap each word in a span for highlighting
        const text = block
            .map((w, idx) => `<c.word-${i + idx}>${w.word}</c>`)
            .join(' ');

        vtt += `${start} --> ${end}\n${text}\n\n`;
    }

    // 4️. Create a blob URL
    const blob = new Blob([vtt], { type: 'text/vtt' });
    const srcUrl = URL.createObjectURL(blob);
    const textTrackOptions = [{
        src: srcUrl,
        kind: 'subtitles' as 'subtitles',
        srclang: transcriptData.languageCode || 'en',
        label: 'AI Gen Subtitles',
        default: opts.default || false,
    }]

    if (wordHighlight) {
        let subtitleSyncInterval: any;

        player.on('play', () => {
            subtitleSyncInterval = setInterval(() => {
                const time = player.currentTime();
                const display = player.el().querySelector('.vjs-text-track-display');
                if (!display) return;

                display.querySelectorAll('span[class^="word-"], span[class*=" word-"]').forEach(el => {
                    const cls = Array.from(el.classList)
                        .find(c => c.startsWith('word-'))!;
                    const idx = Number(cls.split('-')[1]);
                    const w = allWords[idx];
                    el.classList.toggle('vjs-word-highlight', (time ?? 0) >= w.start && (time ?? 0) <= w.end);
                });
            }, 50); // every 100ms
        });

        player.on('pause', () => {
            clearInterval(subtitleSyncInterval);
        });
        player.on('ended', () => {
            clearInterval(subtitleSyncInterval);
        });
    }

    if (isTranslate(opts)) {
        opts.translate.map(async (t, index) => {
            const langCode = t.langCode.toLowerCase();
            const label = t.label || `Translated (${langCode})`;
            return textTrackOptions.push({
                src: srcUrls[index + 1], // Access the correct index for translated URLs
                kind: 'subtitles',
                srclang: langCode,
                label,
                default: t.default || false,
            });
        });

    }
    console.log('Final textTrackOptions:', textTrackOptions);
    return textTrackOptions;
}

function hasSrc(opts: RemoteTextTrackOptions): opts is TextTrackOptions & { src: string } {
    return typeof (opts as any).src === 'string';
}

function isAutoGenerate(opts: RemoteTextTrackOptions): opts is AutoGeneratedTextTrackOptions {
    return (opts as any).autoGenerateSubtitles === true;
}

function isTranslate(opts: RemoteTextTrackOptions): opts is AutoGeneratedTextTrackOptions & { translate: Array<{ langCode: string; label?: string; default?: boolean }> } {
    return (opts as any).translate && Array.isArray((opts as any).translate);
}


export function validateRemoteTextTrackOptions(opts: RemoteTextTrackOptions): void {
    // Invalid: src/kind/srclang/label with auto-generation
    if (isAutoGenerate(opts)) {
        const conflicting = ['src', 'kind', 'srclang', 'label'].filter(key => key in opts);
        if (conflicting.length > 0) {
            throw new Error(
                `Invalid RemoteTextTrackOptions: Cannot specify [${conflicting.join(', ')}] when autoGenerateSubtitles is true.`
            );
        }

        if (opts.translate?.length && (opts.maxWords || opts.wordHighlight)) {
            throw new Error(
                `Invalid RemoteTextTrackOptions: Cannot use maxWords or wordHighlight when translate is provided.`
            );
        }
    }
    // Invalid: if src is not a transcript URL, and maxWords/wordHighlight is set
    if (hasSrc(opts) && (opts.maxWords || opts.wordHighlight)) {
        const srcURL = new URL(opts.src);
        const isTranscript = srcURL.pathname.endsWith('.transcript');
        if (!isTranscript) {
            throw new Error(
                `Invalid RemoteTextTrackOptions: src must be a transcript URL when using maxWords or wordHighlight.`
            );
        }
    }

    // Validate translate array
    if (isTranslate(opts)) {

        // Invalid: translate without auto-generation
        if (!isAutoGenerate(opts)) {
            throw new Error(
                `Invalid RemoteTextTrackOptions: translate can only be used with autoGenerateSubtitles.`
            );
        }
        // Invalid: translate with maxWords or wordHighlight
        if (opts.maxWords || opts.wordHighlight) {
            throw new Error(
                `Invalid RemoteTextTrackOptions: translate cannot be used with maxWords or wordHighlight.`
            );
        }

        // Translate must be an array
        if (!Array.isArray(opts.translate)) {
            throw new Error(`Invalid translate option: must be an array.`);
        }

        // Validate each translate entry
        // There should only be one default
        const defaultCount = opts.translate.filter(t => t.default).length + ((opts.default) ? 1 : 0);
        if (defaultCount > 1) {
            throw new Error(`Invalid translate option: only one entry can have default set to true.`);
        }
        opts.translate.forEach((t, idx) => {
            if (!t.langCode || typeof t.langCode !== 'string') {
                throw new Error(`Invalid translate option at index ${idx}: langCode is required and must be a string.`);
            }
            if (!languageCodes[t.langCode.toLowerCase()]) {
                throw new Error(`Invalid translate option at index ${idx}: langCode "${t.langCode}" is not supported.`);
            }
            if (t.label && typeof t.label !== 'string') {
                throw new Error(`Invalid translate option at index ${idx}: label must be a string.`);
            }
            if (t.default && typeof t.default !== 'boolean') {
                throw new Error(`Invalid translate option at index ${idx}: default must be a boolean.`);
            }
        });
    }
}


export function overrideAddRemoteTextTrack(
    player: Player,
    getOriginalFirstSource: () => SourceOptions | null,
    signerFn?: (src: string) => Promise<string> | undefined
) {
    const orig = player.addRemoteTextTrack.bind(player);

    player.addRemoteTextTrack = (
        options: RemoteTextTrackOptions,
        manualCleanup?: boolean
    ) => {

        const currentSource = getOriginalFirstSource();
        // If no current source, return early
        if (!currentSource) {
            player.error('No current source available for subtitles.');
            return;
        }

        // 1) Validate options
        try {
            validateRemoteTextTrackOptions(options);
        } catch (err) {
            player.error(err instanceof Error ? err.message : String(err));
            return;
        }

        // 2) Check if src is a transcript URL
        const srcURL = hasSrc(options) ? new URL(options.src) : null;
        const isTranscript = srcURL && srcURL.pathname.endsWith('.transcript');

        // 3) Create the track element immediately if signerFn not provided
        let trackEl: HTMLTrackElement | undefined;
        if (!signerFn) {
            trackEl = orig({
                kind: 'subtitles',
                src: 'src' in options && !isTranscript && options.src || '',
                srclang: 'srclang' in options && options.srclang || 'en',
                label: 'label' in options && options.label || 'Loading…',
                default: options.default ?? false,
            }, manualCleanup) as HTMLTrackElement;
        }
        else {

            // 3) Create a placeholder track element with "Loading…" label
            trackEl = orig({
                kind: 'subtitles',
                src: '',
                srclang: 'en',
                label: 'Loading…',
                default: options.default ?? false,
            }, manualCleanup) as HTMLTrackElement;
        }



        // 4) if we need to auto‐generate, fire off the async work now
        if (isAutoGenerate(options) || isTranscript) {
            setupSubtitles({ player: player, opts: options, signerFn, currentSource })
                .then(async (finalOpts) => {
                    // finalOpts.src is a Blob URL with your full VTT 
                    const src = finalOpts[0].src!;
                    const vttText = await fetch(src).then(r => r.text());

                    // 3) parse the VTT yourself and add cues to the same TextTrack
                    //    (video.js bundles vtt.js under window.WebVTT)
                    const parser = new (window as any).WebVTT.Parser(
                        window,
                        //@ts-ignore    
                        WebVTT.StringDecoder()
                    );
                    const cues: TextTrackCue[] = [];
                    parser.oncue = (c: TextTrackCue) => cues.push(c);
                    parser.parse(vttText);
                    parser.flush();

                    // 4) clear out the “Loading…” label and replace with your real one
                    // console.log('trackEl:', trackEl);
                    trackEl.label = finalOpts[0].label;
                    trackEl.srclang = finalOpts[0].srclang;
                    // 5) enable the track
                    //@ts-ignore    
                    trackEl.track!.mode = 'hidden';

                    // 6) add all the real cues
                    //@ts-ignore    
                    cues.forEach(cue => trackEl.track!.addCue(cue));
                    //@ts-ignore   
                    trackEl.track.default = finalOpts[0].default;
                    //@ts-ignore  
                    trackEl.track.label = finalOpts[0].label;

                    //@ts-ignore  
                    const tt = trackEl.track!;

                    if (finalOpts[0].default) {
                        // 1) force it to show
                        tt.mode = 'showing';

                        // 2) turn _off_ every other textTrack so yours is the only one
                        //@ts-ignore  
                        for (const other of Array.from(player.textTracks())) {
                            if (other !== tt) {
                                //@ts-ignore  
                                other.mode = 'disabled';
                            }
                        }
                    }


                    // add the rest of the text tracks
                    if (finalOpts.length > 1) {
                        finalOpts.slice(1).forEach(opt => {
                            // add each translated track
                            // console.log('Adding translated track:', opt);
                            const track: HTMLTrackElement | undefined = orig({
                                kind: 'subtitles',
                                src: opt.src,
                                srclang: opt.srclang,
                                label: opt.label,
                                default: opt.default ?? false,
                            }, manualCleanup);

                        
                        // Check if the current track matches our intended default track.
                        // console.log('track in translated:', track);
                        if (opt.default) {
                            console.log(`Setting track ${opt.label} as default`);
                            // @ts-ignore
                            track.track.mode = 'showing';
                            // @todo tried this it did not work
                             //@ts-ignore 
                            for (const other of Array.from(player.textTracks())) {
                                // @ts-ignore
                                if (other !== track.track) {
                                    //@ts-ignore  
                                    other.mode = 'disabled';
                                }
                            }
                        } else {
                            // Ensure all other tracks are not showing.
                            // @ts-ignore
                            track.track.mode = 'disabled';
                        }
                        });
                    }

                    // @todo Check if it requires, we need to solve the problem of defaulting to translated options
                    // await new Promise(resolve => setTimeout(resolve, 0));


                    // 7) finally, rebuild the Subs/Caps button so it picks up the new label/default
                    // @ts-ignore
                    const ccButton = player.controlBar.getChild('SubsCapsButton') as any;
                    if (ccButton && typeof ccButton.update === 'function') {
                        ccButton.update();
                    }

                })
                .catch(err => {
                    player.log.warn(`Subtitle setup failed: ${err instanceof Error ? err.message : String(err)}`);
                });
        }

        // 7) return the *same* HTMLTrackElement you just mutated later
        return trackEl;
    };
}

async function prepareSubtitleSrc(
    input: RemoteTextTrackOptions,
    currentSource: SourceOptions,
    signerFn?: (src: string) => Promise<string> | undefined

): Promise<string[]> {
    let src: string = "";
    if (hasSrc(input)) {
        const url = new URL(input.src);
        // If signer function is provided, sign the URL
        if (signerFn) {
            try {
                src = await signerFn(url.toString());
            } catch (err) {
                throw new Error(`Failed to sign subtitle URL: ${err instanceof Error ? err.message : String(err)}`);
            }
        } else {
            src = url.toString();
        }

        return [src];
    }

    else if (isAutoGenerate(input)) {
        // generate transcipt url
        const transcriptUrl = new URL(currentSource.src!);
        if (transcriptUrl.pathname.endsWith('ik-master.m3u8')) {
            transcriptUrl.pathname = transcriptUrl.pathname.replace(/ik-master\.m3u8$/, 'ik-gensubtitle.transcript');
        } else if (transcriptUrl.pathname.endsWith('ik-master.mpd')) {
            transcriptUrl.pathname = transcriptUrl.pathname.replace(/ik-master\.mpd$/, 'ik-gensubtitle.transcript');
        } else {
            transcriptUrl.pathname = `${transcriptUrl.pathname.replace(/\/$/, '')}/ik-gensubtitle.transcript`;
        }
        src = transcriptUrl.toString();

        // generate translation URLs if needed
        let translatedUrls: string[] = [];
        if (isTranslate(input)) {
            translatedUrls = input.translate.map(t => {
                const langCode = t.langCode.toLowerCase();
                const translatedUrl = new URL(transcriptUrl.toString());
                // replace .transcript with .vtt
                translatedUrl.pathname = translatedUrl.pathname.replace(/\.transcript$/, `.vtt`);
                // add query param tr=lang-{language-code}
                translatedUrl.searchParams.set('tr', `lang-${langCode}`);
                return translatedUrl.toString();
            })
        }
        if (signerFn) {
            try {
                // Sign the main transcript URL
                src = await signerFn(transcriptUrl.toString());
                // Sign each translated URL if signer function is provided
                translatedUrls = await Promise.all(translatedUrls.map(url => signerFn!(url)));
            } catch (err) {
                throw new Error(`Failed to sign subtitle URLs: ${err instanceof Error ? err.message : String(err)}`);
            }
        }

        return [src, ...translatedUrls];
    }
    return [src];
}