import type Player from 'video.js/dist/types/player';
import type HTMLTrackElement from 'video.js/dist/types/tracks/html-track-element.d.ts';
import type TextTrack from 'video.js/dist/types/tracks/text-track';
import { languageCodes } from '../../interfaces';
import type { AutoGeneratedTextTrackOptions, RemoteTextTrackOptions, SourceOptions, TextTrackOptions } from '../../interfaces';

declare module 'video.js' {
    interface HtmlTrackElement {
        track: TextTrack;
    }
}

interface CaptionData {
    startTime: number;
    endTime: number;
    text: string;
}

interface SubtitleTrackData {
    captions: CaptionData[];
    languageCode: string;
    label: string;
    default: boolean;
}

const DEFAULT_AI_GENERATED_SUBTITLE_LABEL = 'AI Gen Subtitles';

function hasSrc(opts: RemoteTextTrackOptions): opts is TextTrackOptions & { src: string } {
    return typeof (opts as any).src === 'string';
}

function isAutoGenerate(opts: RemoteTextTrackOptions): opts is AutoGeneratedTextTrackOptions {
    return (opts as any).autoGenerateSubtitles === true;
}

function isTranslate(opts: RemoteTextTrackOptions): opts is AutoGeneratedTextTrackOptions & { translate: Array<{ langCode: string; label?: string; default?: boolean }> } {
    return (opts as any).translate && Array.isArray((opts as any).translate);
}

/**
 * Convert language code to a readable language name
 * Example: 'en' -> 'English', 'es' -> 'Spanish'
 */
function getLanguageName(langCode: string): string {
    const code = langCode.toLowerCase();
    const languageName = languageCodes[code as keyof typeof languageCodes];

    if (!languageName) {
        return langCode;
    }

    return languageName
        .split('_')
        .map(word => word.charAt(0) + word.slice(1).toLowerCase())
        .join(' ');
}

function disableOtherTracks(player: Player, activeTrack: any): void {
    //@ts-ignore
    for (const other of Array.from(player.textTracks())) {
        if (other !== activeTrack) {
            //@ts-ignore
            other.mode = 'disabled';
        }
    }
}

export function validateRemoteTextTrackOptions(opts: RemoteTextTrackOptions): void {
    if (isAutoGenerate(opts)) {
        const conflicting = ['src', 'kind', 'srclang'].filter(key => key in opts);
        if (conflicting.length > 0) {
            throw new Error(
                `Invalid RemoteTextTrackOptions: Cannot specify [${conflicting.join(', ')}] when autoGenerateSubtitles is true.`
            );
        }

        if (opts.translate?.length && (opts.maxWords || opts.wordHighlight)) {
            throw new Error(
                `Invalid RemoteTextTrackOptions: Cannot use maxWords or wordHighlight when translate is provided.`
            );
        }
    }

    if (hasSrc(opts) && (opts.maxWords || opts.wordHighlight)) {
        const srcURL = new URL(opts.src);
        const isTranscript = srcURL.pathname.endsWith('.transcript');
        if (!isTranscript) {
            throw new Error(
                `Invalid RemoteTextTrackOptions: src must be a transcript URL when using maxWords or wordHighlight.`
            );
        }
    }

    if (isTranslate(opts)) {
        if (!isAutoGenerate(opts)) {
            throw new Error(
                `Invalid RemoteTextTrackOptions: translate can only be used with autoGenerateSubtitles.`
            );
        }

        if (opts.maxWords || opts.wordHighlight) {
            throw new Error(
                `Invalid RemoteTextTrackOptions: translate cannot be used with maxWords or wordHighlight.`
            );
        }

        if (!Array.isArray(opts.translate)) {
            throw new Error(`Invalid translate option: must be an array.`);
        }

        const defaultCount = opts.translate.filter(t => t.default).length + ((opts.default) ? 1 : 0);
        if (defaultCount > 1) {
            throw new Error(`Invalid translate option: only one entry can have default set to true.`);
        }

        opts.translate.forEach((t, idx) => {
            if (!t.langCode || typeof t.langCode !== 'string') {
                throw new Error(`Invalid translate option at index ${idx}: langCode is required and must be a string.`);
            }
            if (!languageCodes[t.langCode.toLowerCase()]) {
                throw new Error(`Invalid translate option at index ${idx}: langCode "${t.langCode}" is not supported.`);
            }
            if (t.label && typeof t.label !== 'string') {
                throw new Error(`Invalid translate option at index ${idx}: label must be a string.`);
            }
            if (t.default && typeof t.default !== 'boolean') {
                throw new Error(`Invalid translate option at index ${idx}: default must be a boolean.`);
            }
        });
    }
}

async function generateCaptions(params: {
    opts: RemoteTextTrackOptions;
    transcriptUrl: string;
}): Promise<SubtitleTrackData | null> {
    let { opts, transcriptUrl } = params;
    const { maxWords = 4, wordHighlight } = opts;

    const raw = await fetch(transcriptUrl).then(r => {
        if (!r.ok) throw new Error('Failed to fetch transcript');
        return r.text();
    });

    const transcriptData = JSON.parse(raw) as {
        languageCode: string;
        transcript: Array<{
            transcript: string;
            confidence: number;
            words: Array<{
                word: string;
                start: number;
                end: number;
            }>;
        }>;
        paragraphs?: Array<{
            text: string;
            start: number;
            end: number;
            confidence: number;
        }>;
    };

    const entries = transcriptData.transcript;

    const parseTranscript = (): CaptionData[] => {
        const captions: CaptionData[] = [];

        const addCaption = ({ startTime, endTime, text }: CaptionData) => {
            captions.push({ startTime, endTime, text });
        };

        entries.forEach(segment => {
            const words = segment.words;

            if (words && words.length > 0) {
                if (wordHighlight) {
                    for (let i = 0; i < words.length; i += maxWords) {
                        const block = words.slice(i, Math.min(i + maxWords, words.length));

                        block.forEach((word, idx) => {
                            addCaption({
                                startTime: word.start,
                                endTime: word.end,
                                text: block
                                    .map(w => (w === word ? `<c.vjs-word-highlight>${w.word}</c>` : w.word))
                                    .join(' ')
                            });

                            if (block[idx + 1] && word.end < block[idx + 1].start) {
                                addCaption({
                                    startTime: word.end,
                                    endTime: block[idx + 1].start,
                                    text: block.map(w => w.word).join(' ')
                                });
                            }
                        });
                    }
                } else {
                    for (let i = 0; i < words.length; i += maxWords) {
                        const block = words.slice(i, Math.min(i + maxWords, words.length));
                        addCaption({
                            startTime: block[0].start,
                            endTime: block[block.length - 1].end,
                            text: block.map(w => w.word).join(' ')
                        });
                    }
                }
            } else {
                addCaption({
                    startTime: (segment as any).start_time || 0,
                    endTime: (segment as any).end_time || 0,
                    text: segment.transcript
                });
            }
        });

        return captions;
    };

    const captions = parseTranscript();

    return {
        captions,
        languageCode: transcriptData.languageCode || 'en',
        label: (isAutoGenerate(opts) && opts.label) ? opts.label : DEFAULT_AI_GENERATED_SUBTITLE_LABEL,
        default: opts.default || false,
    };
}

async function prepareSubtitleSrc(
    input: RemoteTextTrackOptions,
    currentSource: SourceOptions,
    signerFn?: (src: string) => Promise<string> | undefined
): Promise<string[]> {
    let src: string = "";
    if (!hasSrc(input) && !isAutoGenerate(input)) {
        throw new Error('Invalid RemoteTextTrackOptions: src or autoGenerateSubtitles is required');
    }

    if (hasSrc(input)) {
        const url = new URL(input.src);
        if (signerFn) {
            try {
                src = await signerFn(url.toString());
            } catch (err) {
                throw new Error(`Failed to sign subtitle URL: ${err instanceof Error ? err.message : String(err)}`);
            }
        } else {
            src = url.toString();
        }
        return [src];
    }

    if (isAutoGenerate(input)) {
        if (!currentSource.src) {
            throw new Error('Cannot generate subtitles: video source URL is missing');
        }
        const transcriptUrl = new URL(currentSource.src);
        if (transcriptUrl.pathname.endsWith('ik-master.m3u8')) {
            transcriptUrl.pathname = transcriptUrl.pathname.replace(/ik-master\.m3u8$/, 'ik-gensubtitle.transcript');
        } else if (transcriptUrl.pathname.endsWith('ik-master.mpd')) {
            transcriptUrl.pathname = transcriptUrl.pathname.replace(/ik-master\.mpd$/, 'ik-gensubtitle.transcript');
        } else {
            transcriptUrl.pathname = `${transcriptUrl.pathname.replace(/\/$/, '')}/ik-gensubtitle.transcript`;
        }
        src = transcriptUrl.toString();

        let translatedUrls: string[] = [];
        if (isTranslate(input)) {
            translatedUrls = input.translate.map(t => {
                const langCode = t.langCode.toLowerCase();
                const translatedUrl = new URL(transcriptUrl.toString());
                translatedUrl.pathname = translatedUrl.pathname.replace(/\.transcript$/, `.vtt`);
                translatedUrl.searchParams.set('tr', `lang-${langCode}`);
                return translatedUrl.toString();
            });
        }

        if (signerFn) {
            try {
                const signer = signerFn;
                src = await signer(transcriptUrl.toString());
                translatedUrls = await Promise.all(translatedUrls.map(url => signer(url)));
            } catch (err) {
                throw new Error(`Failed to sign subtitle URLs: ${err instanceof Error ? err.message : String(err)}`);
            }
        }

        return [src, ...translatedUrls];
    }
}

async function initSubtitles(
    player: Player,
    trackEl: HTMLTrackElement,
    options: RemoteTextTrackOptions,
    signerFn: ((src: string) => Promise<string> | undefined) | undefined,
    currentSource: SourceOptions,
    originalAddRemoteTextTrack: (options: any, manualCleanup?: boolean) => HTMLTrackElement,
    manualCleanup?: boolean
): Promise<void> {
    try {
        const srcUrls: string[] = await prepareSubtitleSrc(options, currentSource, signerFn);
        if (srcUrls.length === 0 || !srcUrls[0]) {
            throw new Error('Failed to prepare subtitle source URLs');
        }

        const trackData = await generateCaptions({
            opts: options,
            transcriptUrl: srcUrls[0]
        });

        if (!trackData) {
            throw new Error('Failed to setup subtitles: no track data returned');
        }

        trackEl.label = trackData.label;
        trackEl.srclang = trackData.languageCode;

        //@ts-ignore
        if (!trackEl.track) {
            throw new Error('Track element does not have an associated text track');
        }
        //@ts-ignore
        const textTrack = trackEl.track;
        textTrack.label = trackData.label;
        textTrack.default = trackData.default;

        trackData.captions.forEach(caption => {
            textTrack.addCue(new VTTCue(caption.startTime, caption.endTime, caption.text));
        });

        textTrack.mode = trackData.default ? 'showing' : 'hidden';

        if (trackData.default) {
            disableOtherTracks(player, textTrack);
        }

        if (isTranslate(options)) {
            for (let index = 0; index < options.translate.length; index++) {
                const t = options.translate[index];
                const langCode = t.langCode.toLowerCase();
                const languageName = getLanguageName(langCode);
                const label = t.label || `${languageName} (AI generated)`;
                const vttUrl = srcUrls[index + 1];

                if (vttUrl) {
                    const translatedTrack = originalAddRemoteTextTrack({
                        kind: 'subtitles',
                        src: vttUrl,
                        srclang: langCode,
                        label,
                        default: t.default ?? false,
                        mode: t.default ? 'showing' : 'disabled',
                    }, manualCleanup) as HTMLTrackElement;

                    //@ts-ignore
                    if (!translatedTrack.track) {
                        continue;
                    }

                    //@ts-ignore
                    const translatedTextTrack = translatedTrack.track;

                    if (t.default) {
                        //@ts-ignore
                        translatedTextTrack.mode = 'showing';
                        disableOtherTracks(player, translatedTextTrack);
                    } else {
                        //@ts-ignore
                        translatedTextTrack.mode = 'disabled';
                    }
                }
            }
        }

        //@ts-ignore
        const ccButton = player.controlBar.getChild('SubsCapsButton') as any;
        if (ccButton && typeof ccButton.update === 'function') {
            ccButton.update();
        }

    } catch (err) {
        player.log.warn(`Subtitle setup failed: ${err instanceof Error ? err.message : String(err)}`);
        trackEl.label = 'Failed to load subtitles';
    }
}

export function overrideAddRemoteTextTrack(
    player: Player,
    getOriginalFirstSource: () => SourceOptions | null,
    signerFn?: (src: string) => Promise<string> | undefined
) {
    const originalAddRemoteTextTrack = player.addRemoteTextTrack.bind(player);

    player.addRemoteTextTrack = (
        options: RemoteTextTrackOptions,
        manualCleanup?: boolean
    ) => {

        const currentSource = getOriginalFirstSource();
        if (!currentSource) {
            player.error('No current source available for subtitles.');
            return;
        }

        try {
            validateRemoteTextTrackOptions(options);
        } catch (err) {
            player.error(err instanceof Error ? err.message : String(err));
            return;
        }

        const srcURL = hasSrc(options) ? new URL(options.src) : null;
        const isTranscript = srcURL && srcURL.pathname.endsWith('.transcript');

        // Handle auto-generated subtitles or transcript files
        if (isAutoGenerate(options) || isTranscript) {
            const trackEl = originalAddRemoteTextTrack({
                kind: 'subtitles',
                src: '',
                srclang: 'en',
                label: options.label || DEFAULT_AI_GENERATED_SUBTITLE_LABEL,
                default: options.default ?? false,
            }, manualCleanup) as HTMLTrackElement;


            if (player.readyState() >= 1) {
                initSubtitles(player, trackEl, options, signerFn, currentSource, originalAddRemoteTextTrack, manualCleanup);
            } else {
                player.one('loadedmetadata', () => {
                    initSubtitles(player, trackEl, options, signerFn, currentSource, originalAddRemoteTextTrack, manualCleanup);
                });
            }

            return trackEl;
        }

        // For regular subtitles with src, use the original method
        return originalAddRemoteTextTrack({
            kind: 'subtitles',
            src: options.src || '',
            srclang: options.srclang || 'en',
            label: options.label || 'Subtitles',
            default: options.default ?? false,
        }, manualCleanup) as HTMLTrackElement;
    };
}