import type Player from 'video.js/dist/types/player';
import type HTMLTrackElement from 'video.js/dist/types/tracks/html-track-element.d.ts';
import type TextTrack from 'video.js/dist/types/tracks/text-track';
import { languageCodes } from '../../interfaces';
import type { AutoGeneratedTextTrackOptions, RemoteTextTrackOptions, SourceOptions, TextTrackOptions } from '../../interfaces';
import { filterTrQueryParam } from '../../utils';

declare module 'video.js' {
    interface HtmlTrackElement {
        track: TextTrack;
    }
}

interface CaptionData {
    startTime: number;
    endTime: number;
    text: string;
}

interface SubtitleTrackData {
    captions: CaptionData[];
    languageCode: string;
    label: string;
    default: boolean;
}

interface TimedWord {
    word: string;
    start: number;
    end: number;
}

interface TranscriptSegment {
    transcript: string;
    confidence: number;
    words: Array<TimedWord>;
}

interface TranscriptParagraph {
    text: string;
    start: number;
    end: number;
    confidence: number;
}

interface TranscriptData {
    languageCode: string;
    transcript: Array<TranscriptSegment>;
    paragraphs?: Array<TranscriptParagraph>;
}

const DEFAULT_AI_GENERATED_SUBTITLE_LABEL = 'Auto-generated Subtitles';

const ALLOWED_TRANSFORM_PARAMS_SUBTITLES = new Set(['so', 'eo', 'du']);

const MAX_TIME_GAP_SECONDS = 3;
const DEFAULT_MAX_CHARS = 60;
const READY_STATE_HAVE_METADATA = 1;

// Module-level logger for subtitle functions
let moduleLogger: { warn?: (msg: string) => void; error?: (msg: string) => void } | null = null;

/**
 * Set the logger for subtitle module functions
 */
function setLogger(logger: { warn?: (msg: string) => void; error?: (msg: string) => void }): void {
    moduleLogger = logger;
}

/**
 * Log a warning message using module logger or console fallback
 */
function logWarn(message: string): void {
    if (moduleLogger?.warn) {
        moduleLogger.warn(message);
    } else {
        console.warn(message);
    }
}

/**
 * Log an error message using module logger or console fallback
 */
function logError(message: string): void {
    if (moduleLogger?.error) {
        moduleLogger.error(message);
    } else {
        console.error(message);
    }
}

function hasSrc(opts: RemoteTextTrackOptions): opts is TextTrackOptions & { src: string } {
    return typeof (opts as any).src === 'string';
}

function isAutoGenerate(opts: RemoteTextTrackOptions): opts is AutoGeneratedTextTrackOptions {
    return (opts as any).autoGenerate === true;
}

function isTranslate(opts: RemoteTextTrackOptions): opts is AutoGeneratedTextTrackOptions & { translations: Array<{ langCode: string; label?: string; default?: boolean }> } {
    return (opts as any).translations && Array.isArray((opts as any).translations);
}

/**
 * Convert language code to a readable language name
 * Example: 'en' -> 'English', 'es' -> 'Spanish'
 */
function getLanguageName(langCode: string): string {
    const code = langCode.toLowerCase();
    const languageName = languageCodes[code as keyof typeof languageCodes];

    if (!languageName) {
        return langCode;
    }

    return languageName
        .split('_')
        .map(word => word.charAt(0) + word.slice(1).toLowerCase())
        .join(' ');
}

function disableOtherTracks(player: Player, activeTrack: any): void {
    //@ts-ignore
    for (const other of Array.from(player.textTracks())) {
        if (other !== activeTrack) {
            //@ts-ignore
            other.mode = 'disabled';
        }
    }
}

/**
 * Initialize a function when the player has loaded metadata.
 * If metadata is already loaded, executes immediately; otherwise waits for the 'loadedmetadata' event.
 */
async function initWhenReady(player: Player, initFn: () => void | Promise<void>): Promise<void> {
    if (player.readyState() >= READY_STATE_HAVE_METADATA) {
        await initFn();
    } else {
        player.one('loadedmetadata', async () => await initFn());
    }
}

/**
 * Creates captions with word-level highlighting
 */
function createHighlightedCaptions(
    wordGroups: Array<Array<TimedWord>>,
    addCaption: (caption: CaptionData) => void
): void {
    wordGroups.forEach(block => {
        block.forEach((word, idx) => {
            addCaption({
                startTime: word.start,
                endTime: word.end,
                text: block
                    .map(w => (w === word ? `<c.vjs-word-highlight>${w.word}</c>` : w.word))
                    .join(' ')
            });

            if (block[idx + 1] && word.end < block[idx + 1].start) {
                addCaption({
                    startTime: word.end,
                    endTime: block[idx + 1].start,
                    text: block.map(w => w.word).join(' ')
                });
            }
        });
    });
}

/**
 * Creates regular captions without word highlighting
 */
function createRegularCaptions(
    wordGroups: Array<Array<TimedWord>>,
    addCaption: (caption: CaptionData) => void,
    previousText: string | null = null,
    nextText: string | null = null
): void {
    wordGroups.forEach(block => {
        if (block.length > 0) {
            let text = block.map(w => w.word).join(' ');
            
            // Add context if provided
            if (previousText || nextText) {
                const contextLines: string[] = [];
                if (previousText) contextLines.push(previousText);
                contextLines.push(text);
                if (nextText) contextLines.push(nextText);
                text = contextLines.join('\n');
            }

            addCaption({
                startTime: block[0].start,
                endTime: block[block.length - 1].end,
                text
            });
        }
    });
}

/**
 * Groups words into cues based on character limits and time gaps.
 * Uses a soft limit for equal distribution and a hard limit (maxChars) that is never exceeded.
 */
function groupWordsByChars(
    words: Array<TimedWord>,
    sentenceLength: number,
    maxChars: number,
    maxTimeGap: number
): Array<Array<TimedWord>> {
    const groups: Array<Array<TimedWord>> = [];
    
    // Calculate soft limit for equal distribution of characters across cues
    const divisor = Math.ceil(sentenceLength / maxChars);
    const softLimit = Math.floor(sentenceLength / divisor);

    let currentGroup: Array<TimedWord> = [];
    let currentLine = "";
    let lastEnd = words[0]?.start;

    words.forEach((word, ind) => {
            // Validate individual word length
            if (word.word.length > maxChars) {
                logWarn(`Individual word "${word.word}" is longer than maxChars (${maxChars})`);
            }

        const gap = word.start - lastEnd;
        const token = (currentLine ? " " : "") + word.word;
        const newLineLength = (currentLine + token).length;

        // Determine if we should create a new cue
        const shouldBreak = 
            (newLineLength > softLimit && newLineLength <= maxChars && gap <= maxTimeGap) ||
            gap > maxTimeGap || 
            newLineLength > maxChars;

        if (shouldBreak && currentGroup.length > 0 && newLineLength > maxChars) {
            // Hard limit exceeded - don't add current word, start new group
            groups.push([...currentGroup]);
            currentGroup = [word];
            currentLine = word.word;
            lastEnd = word.end;
        } else if (shouldBreak && currentGroup.length > 0) {
            // Soft limit or time gap - add current word and start new group
            currentGroup.push(word);
            groups.push([...currentGroup]);
            currentGroup = [];
            currentLine = "";
            lastEnd = ind < words.length - 1 ? words[ind + 1]?.start : word.end;
        } else {
            // Add word to current group
            currentGroup.push(word);
            currentLine += token;
            lastEnd = word.end;
        }

        // Last word of segment
        if (ind === words.length - 1 && currentGroup.length > 0) {
            groups.push(currentGroup);
        }
    });

    return groups;
}

export function validateRemoteTextTrackOptions(opts: RemoteTextTrackOptions): void {
    if (isAutoGenerate(opts)) {
        const conflicting = ['src', 'kind', 'srclang'].filter(key => key in opts);
        if (conflicting.length > 0) {
            throw new Error(
                `Cannot specify [\`${conflicting.join('`, `')}\`] when \`autoGenerate\` is true.`
            );
        }


        if (opts.showAutoGenerated !== undefined && typeof opts.showAutoGenerated !== 'boolean') {
            throw new Error(
                '`showAutoGenerated` must be a boolean.'
            );
        }
    }

    if (hasSrc(opts) && (opts.maxChars || opts.highlightWords)) {
        const srcURL = new URL(opts.src);
        const isTranscript = srcURL.pathname.endsWith('.transcript');
        if (!isTranscript) {
            throw new Error(
                '`src` must be a transcript URL when using `maxChars` or `highlightWords`.'
            );
        }
    }

    // Validate showAutoGenerated: false requires translations
    if (isAutoGenerate(opts) && opts.showAutoGenerated === false) {
        if (!isTranslate(opts) || opts.translations.length === 0) {
            throw new Error(
                '`showAutoGenerated`: false only makes sense when `translations` are provided.'
            );
        }
    }

    if (isTranslate(opts)) {
        if (!isAutoGenerate(opts)) {
            throw new Error(
                '`translations` can only be used with `autoGenerate`.'
            );
        }

        if (opts.maxChars || opts.highlightWords) {
            throw new Error(
                '`translations` cannot be used with `maxChars` or `highlightWords`.'
            );
        }

        if (!Array.isArray(opts.translations)) {
            throw new Error('`translations` must be an array.');
        }

        const defaultCount = opts.translations.filter(t => t.default).length + ((opts.default) ? 1 : 0);
        if (defaultCount > 1) {
            throw new Error('`translations`: only one entry can have `default` set to true.');
        }

        opts.translations.forEach((t, idx) => {
            if (!t.langCode || typeof t.langCode !== 'string') {
                throw new Error(`\`translations[${idx}].langCode\` is required and must be a string.`);
            }
            if (!languageCodes[t.langCode.toLowerCase()]) {
                throw new Error(`\`translations[${idx}].langCode\` "${t.langCode}" is not supported.`);
            }
            if (t.label && typeof t.label !== 'string') {
                throw new Error(`\`translations[${idx}].label\` must be a string.`);
            }
            if (t.default && typeof t.default !== 'boolean') {
                throw new Error(`\`translations[${idx}].default\` must be a boolean.`);
            }
        });
    }
}

async function generateCaptions(params: {
    opts: RemoteTextTrackOptions;
    transcriptUrl: string;
}): Promise<SubtitleTrackData | null> {
    let { opts, transcriptUrl } = params;
    const maxChars = opts.maxChars ?? DEFAULT_MAX_CHARS;
    const highlightWords = opts.highlightWords ?? false;

    const raw = await fetch(transcriptUrl).then(r => {
        if (!r.ok) throw new Error('Failed to fetch transcript');
        return r.text();
    });

    const transcriptData = JSON.parse(raw) as TranscriptData;

    const entries = transcriptData.transcript;

    const parseTranscript = (): CaptionData[] => {
        const captions: CaptionData[] = [];
        const maxTimeGap = MAX_TIME_GAP_SECONDS;
        const addCaption = ({ startTime, endTime, text }: CaptionData) => {
            captions.push({ startTime, endTime, text });
        };


        // Process each segment
        entries.forEach(segment => {
            const words = segment.words;

            if (words && words.length > 0) {
                const sentenceLength = segment.transcript.length;
                const wordGroups = groupWordsByChars(words, sentenceLength, maxChars, maxTimeGap);

                if (highlightWords) {
                    createHighlightedCaptions(wordGroups, addCaption);
                } else {
                    createRegularCaptions(wordGroups, addCaption);
                }
            } else {
                // Fallback for segments without word-level timing
                addCaption({
                    startTime: (segment as any).start_time || 0,
                    endTime: (segment as any).end_time || 0,
                    text: segment.transcript
                });
            }
        });

        return captions;
    };

    const captions = parseTranscript();

    return {
        captions,
        languageCode: transcriptData.languageCode || 'en',
        label: (isAutoGenerate(opts) && opts.autoGeneratedLabel) ? opts.autoGeneratedLabel : `${getLanguageName(transcriptData.languageCode)} (auto-generated)`,
        default: opts.default || false,
    };
}

async function prepareSubtitleSrc(
    input: RemoteTextTrackOptions,
    currentSource: SourceOptions,
    signerFn?: (src: string) => Promise<string> | undefined
): Promise<string[]> {
    let src: string = "";
    if (!hasSrc(input) && !isAutoGenerate(input)) {
        throw new Error('Invalid RemoteTextTrackOptions: src or autoGenerate is required');
    }

    if (hasSrc(input)) {
        const url = new URL(input.src);
        if (signerFn) {
            try {
                src = await signerFn(url.toString());
            } catch (err) {
                throw new Error(`Failed to sign subtitle URL: ${err instanceof Error ? err.message : String(err)}`);
            }
        } else {
            src = url.toString();
        }
        return [src];
    }

    if (isAutoGenerate(input)) {
        if (!currentSource.src) {
            throw new Error('Cannot generate subtitles: video source URL is missing');
        }
        const transcriptUrl = new URL(currentSource.src);
        if (transcriptUrl.pathname.endsWith('ik-master.m3u8')) {
            transcriptUrl.pathname = transcriptUrl.pathname.replace(/ik-master\.m3u8$/, 'ik-gensubtitle.transcript');
        } else if (transcriptUrl.pathname.endsWith('ik-master.mpd')) {
            transcriptUrl.pathname = transcriptUrl.pathname.replace(/ik-master\.mpd$/, 'ik-gensubtitle.transcript');
        } else {
            transcriptUrl.pathname = `${transcriptUrl.pathname.replace(/\/$/, '')}/ik-gensubtitle.transcript`;
        }

        filterTrQueryParam(transcriptUrl, ALLOWED_TRANSFORM_PARAMS_SUBTITLES);
        src = transcriptUrl.toString();

        let translatedUrls: string[] = [];
        if (isTranslate(input)) {
            translatedUrls = input.translations.map(t => {
                const langCode = t.langCode.toLowerCase();
                const translatedUrl = new URL(transcriptUrl.toString());
                translatedUrl.pathname = translatedUrl.pathname.replace(/\.transcript$/, `.vtt`);
                
                const existingTr = translatedUrl.searchParams.get('tr');
                if (existingTr) {
                    translatedUrl.searchParams.set('tr', `${existingTr},lang-${langCode}`);
                } else {
                    translatedUrl.searchParams.set('tr', `lang-${langCode}`);
                }

                return translatedUrl.toString();
            });
        }

        if (signerFn) {
            try {
                const signer = signerFn;
                [src, ...translatedUrls] = await Promise.all([signer(src), ...translatedUrls.map(url => signer(url))]);
            } catch (err) {
                throw new Error(`Failed to sign subtitle URLs: ${err instanceof Error ? err.message : String(err)}`);
            }
        }

        return [src, ...translatedUrls];
    }
}

/**
 * Initialize a base auto-generated text track
 */
async function initBaseTrack(
    player: Player,
    trackEl: HTMLTrackElement,
    options: RemoteTextTrackOptions,
    transcriptUrl: string
): Promise<void> {
    const trackData = await generateCaptions({
        opts: options,
        transcriptUrl
    });

    if (!trackData) {
        throw new Error('Failed to setup subtitles: no track data returned');
    }

    trackEl.label = trackData.label;
    trackEl.srclang = trackData.languageCode;

    //@ts-ignore
    if (!trackEl.track) {
        throw new Error('Track element does not have an associated text track');
    }
    //@ts-ignore
    const textTrack = trackEl.track;
    textTrack.label = trackData.label;
    textTrack.default = trackData.default;

    trackData.captions.forEach(caption => {
        textTrack.addCue(new VTTCue(caption.startTime, caption.endTime, caption.text));
    });

    textTrack.mode = trackData.default ? 'showing' : 'hidden';

    if (trackData.default) {
        disableOtherTracks(player, textTrack);
    }

      //@ts-ignore
      const ccButton = player.controlBar.getChild('SubsCapsButton') as any;
      if (ccButton && typeof ccButton.update === 'function') {
          ccButton.update();
      }
}

/**
 * Parse VTT and convert to synthetic transcript structure with equal time per word
 */
function parseVTTToSyntheticTranscript(vttText: string): Array<{
    transcript: string;
    words: Array<{ word: string; start: number; end: number }>;
}> {
    const segments: Array<{
        transcript: string;
        words: Array<{ word: string; start: number; end: number }>;
    }> = [];

    // Normalize and split into cue blocks
    const rawBlocks = vttText.replace(/\r\n|\r|\n/g, '\n').split(/\n{2,}/);

    for (const block of rawBlocks) {
        const lines = block.trim().split('\n');
        
        // Find the timing line (contains "-->")
        const timeLine = lines.find((l) => /-->/.test(l));
        if (!timeLine) continue;

        // Extract start and end timestamps
        const [startRaw, endRaw] = timeLine.split('-->').map((s) => s.trim());
        const startTime = parseVTTTimestamp(startRaw);
        const endTime = parseVTTTimestamp(endRaw);

        // Get the text (everything after the timing line)
        const timeLineIndex = lines.findIndex((l) => /-->/.test(l));
        const textLines = lines.slice(timeLineIndex + 1);
        const text = textLines.join(' ').trim();

        if (!text || isNaN(startTime) || isNaN(endTime) || endTime <= startTime) {
            continue;
        }

        // Split text into words
        const words = text.split(/\s+/).filter(w => w.length > 0);
        
        if (words.length === 0) continue;

        // Calculate equal time per word
        const duration = endTime - startTime;
        const timePerWord = duration / words.length;

        // Create synthetic word-level timing
        const syntheticWords = words.map((word, index) => ({
            word: word,
            start: startTime + (index * timePerWord),
            end: startTime + ((index + 1) * timePerWord)
        }));

        segments.push({
            transcript: text,
            words: syntheticWords
        });
    }

    return segments;
}

/**
 * Parse VTT timestamp to seconds
 */
function parseVTTTimestamp(timestamp: string): number {
    // Supports both "HH:MM:SS.mmm" and "MM:SS.mmm"
    const parts = timestamp.split(':');
    
    if (parts.length === 3) {
        // HH:MM:SS.mmm
        const hours = parseInt(parts[0], 10);
        const minutes = parseInt(parts[1], 10);
        const seconds = parseFloat(parts[2].replace(',', '.'));
        return hours * 3600 + minutes * 60 + seconds;
    } else if (parts.length === 2) {
        // MM:SS.mmm
        const minutes = parseInt(parts[0], 10);
        const seconds = parseFloat(parts[1].replace(',', '.'));
        return minutes * 60 + seconds;
    }
    
    return 0;
}

/**
 * Format seconds to VTT timestamp (HH:MM:SS.mmm)
 */
function formatVTTTimestamp(seconds: number): string {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = seconds % 60;
    const hoursStr = hours.toString().padStart(2, '0');
    const minutesStr = minutes.toString().padStart(2, '0');
    const secsStr = secs.toFixed(3).padStart(6, '0');
    return `${hoursStr}:${minutesStr}:${secsStr}`;
}

/**
 * Generate captions from VTT (for translations with maxChars support)
 */
async function generateCaptionsFromVTT(params: {
    vttUrl: string;
    maxChars: number;
    label: string;
    defaultTrack: boolean;
}): Promise<SubtitleTrackData | null> {
    const { vttUrl, maxChars, label, defaultTrack } = params;

    try {
        const response = await fetch(vttUrl);
        if (!response.ok) {
            throw new Error(`Failed to fetch VTT: ${response.status}`);
        }
        const vttText = await response.text();

        // Convert VTT to synthetic transcript
        const syntheticSegments = parseVTTToSyntheticTranscript(vttText);

        if (syntheticSegments.length === 0) {
            return null;
        }

        // Use the same caption generation logic as base subtitles
        const captions: CaptionData[] = [];
        const maxTimeGap = MAX_TIME_GAP_SECONDS;

        // First, generate all word groups from all segments
        const allWordGroups: Array<Array<TimedWord>> = [];
        syntheticSegments.forEach((segment) => {
            const words = segment.words;
            const sentenceLength = segment.transcript.length;
            const wordGroups = groupWordsByChars(words, sentenceLength, maxChars, maxTimeGap);
            
            wordGroups.forEach(group => {
                allWordGroups.push(group);
            });
        });

        // Now process each word group with context from previous/next word groups
        allWordGroups.forEach((currentGroup, groupIndex) => {
            const currentText = currentGroup.map(w => w.word).join(' ');
            
            // Get previous word group text if available and within time gap
            let previousText: string | null = null;
            if (groupIndex > 0) {
                const previousGroup = allWordGroups[groupIndex - 1];
                const timeGap = currentGroup[0].start - previousGroup[previousGroup.length - 1].end;
                if (timeGap < maxTimeGap) {
                    previousText = previousGroup.map(w => w.word).join(' ');
                }
            }
            
            // Get next word group text if available and within time gap
            let nextText: string | null = null;
            if (groupIndex < allWordGroups.length - 1) {
                const nextGroup = allWordGroups[groupIndex + 1];
                const timeGap = nextGroup[0].start - currentGroup[currentGroup.length - 1].end;
                if (timeGap < maxTimeGap) {
                    nextText = nextGroup.map(w => w.word).join(' ');
                }
            }
            
            // Build caption text with context
            let text = currentText;
            if (previousText || nextText) {
                const contextLines: string[] = [];
                if (previousText) contextLines.push(previousText);
                contextLines.push(currentText);
                if (nextText) contextLines.push(nextText);
                text = contextLines.join('\n');
            }
            
            captions.push({
                startTime: currentGroup[0].start,
                endTime: currentGroup[currentGroup.length - 1].end,
                text
            });
        });
        
        // Also log as VTT format for easier reading
        const vttOutput = captions.map((caption, index) => {
            const startTime = formatVTTTimestamp(caption.startTime);
            const endTime = formatVTTTimestamp(caption.endTime);
            return `${index + 1}\n${startTime} --> ${endTime}\n${caption.text}`;
        }).join('\n\n');
        // console.log('Final captions as VTT:\nWEBVTT\n\n' + vttOutput);

        return {
            captions,
            languageCode: 'unknown', // Will be set by caller
            label,
            default: defaultTrack,
        };
    } catch (error) {
        logError(`Failed to generate captions from VTT: ${error instanceof Error ? error.message : String(error)}`);
        return null;
    }
}

/**
 * Create translation tracks
 */
function createTranslationTracks(
    player: Player,
    options: AutoGeneratedTextTrackOptions & { translations: Array<{ langCode: string; label?: string; default?: boolean }> },
    translationUrls: string[]
): void {
    const maxChars = DEFAULT_MAX_CHARS;

    options.translations.forEach((t, index) => {
        const langCode = t.langCode.toLowerCase();
        const languageName = getLanguageName(langCode);
        const label = t.label || `${languageName} (auto-generated)`;
        const vttUrl = translationUrls[index];

        if (vttUrl) {
            const translatedTrack = player.addRemoteTextTrack({
                kind: 'subtitles',
                src: '',
                srclang: langCode,
                label,
                default: t.default ?? false,
            }, false) as HTMLTrackElement;

            //@ts-ignore
            if (!translatedTrack.track) {
                return;
            }

            //@ts-ignore
            const translatedTextTrack = translatedTrack.track;

            // Load and process VTT with maxChars support
            const initTranslatedTrack = async () => {
                try {
                    const trackData = await generateCaptionsFromVTT({
                        vttUrl,
                        maxChars,
                        label,
                        defaultTrack: t.default ?? false,
                    });

                    if (!trackData) {
                        throw new Error('Failed to generate captions from VTT');
                    }

                    // Set language code
                    translatedTextTrack.language = langCode;

                    // Add cues to the track
                    trackData.captions.forEach(caption => {
                        translatedTextTrack.addCue(new VTTCue(caption.startTime, caption.endTime, caption.text));
                    });

                    // Set mode
                    if (t.default) {
                        //@ts-ignore
                        translatedTextTrack.mode = 'showing';
                        disableOtherTracks(player, translatedTextTrack);
                    } else {
                        //@ts-ignore
                        translatedTextTrack.mode = 'disabled';
                    }
                } catch (err) {
                    logError(`Failed to load translated track for ${langCode}: ${err instanceof Error ? err.message : String(err)}`);
                    translatedTrack.label = `${label} (failed to load)`;
                }
            };

            // Initialize track when player is ready
            initWhenReady(player, initTranslatedTrack);
        }
    });

    //@ts-ignore
    const ccButton = player.controlBar.getChild('SubsCapsButton') as any;
    if (ccButton && typeof ccButton.update === 'function') {
        ccButton.update();
    }
}

/**
 * Internal function to set text tracks from SourceOptions
 * This is called from player.src() to handle all text tracks at once
 */
export async function setTextTracks(
    player: Player,
    textTracks: RemoteTextTrackOptions[],
    currentSource: SourceOptions,
    signerFn?: (src: string) => Promise<string> | undefined
): Promise<void> {
    // Initialize module logger with player's logger
    setLogger(player.log);

    for (const options of textTracks) {
        try {
            // Validate the options
            validateRemoteTextTrackOptions(options);

            // Handle regular tracks with src (non-transcript)
            if (hasSrc(options)) {
                const srcURL = new URL(options.src);
                const isTranscript = srcURL.pathname.endsWith('.transcript');

                if (!isTranscript) {
                    // Pass through to original addRemoteTextTrack for regular VTT/SRT files
                    const [preparedSrc] = await prepareSubtitleSrc(options, currentSource, signerFn);

                    player.addRemoteTextTrack({
                        kind: options.kind || 'subtitles',
                        src: preparedSrc,
                        srclang: options.srclang || 'en',
                        label: options.label || 'Subtitles',
                        default: options.default ?? false,
                    }, false);
                    continue;
                }
            }

            // Handle auto-generated or transcript files
            if (isAutoGenerate(options) || (hasSrc(options) && new URL(options.src).pathname.endsWith('.transcript'))) {
                const showAutoGenerated = isAutoGenerate(options) ? (options.showAutoGenerated !== false) : true;
                const hasTranslations = isTranslate(options);

                // Prepare subtitle sources (base + translations)
                const srcUrls: string[] = await prepareSubtitleSrc(options, currentSource, signerFn);
                if (srcUrls.length === 0 || !srcUrls[0]) {
                    throw new Error('Failed to prepare subtitle source URLs');
                }

                const baseTranscriptUrl = srcUrls[0];
                const translationUrls = srcUrls.slice(1);

                // Create base auto-generated track only if showAutoGenerated is true
                if (showAutoGenerated) {
                    const label = isAutoGenerate(options)
                        ? (options.autoGeneratedLabel || DEFAULT_AI_GENERATED_SUBTITLE_LABEL)
                        : (options.label || DEFAULT_AI_GENERATED_SUBTITLE_LABEL);

                    const trackEl = player.addRemoteTextTrack({
                        kind: 'subtitles',
                        src: '',
                        srclang: 'en',
                        label: label,
                        default: options.default ?? false,
                    }, false) as HTMLTrackElement;

                    // Initialize base track
                    const initTrack = async () => {
                        try {
                            await initBaseTrack(player, trackEl, options, baseTranscriptUrl);
                        } catch (err) {
                            logError(`Base subtitle setup failed: ${err instanceof Error ? err.message : String(err)}`);
                            trackEl.label = 'Failed to load subtitles';
                        }
                    };

                    await initWhenReady(player, initTrack);
                }

                // Create translation tracks
                if (hasTranslations) {
                    const initTranslations = () => {
                        try {
                            createTranslationTracks(player, options, translationUrls);
                        } catch (err) {
                            logError(`Translation tracks setup failed: ${err instanceof Error ? err.message : String(err)}`);
                        }
                    };

                    initWhenReady(player, initTranslations);
                }
            }
        } catch (err) {
            logError(`Failed to setup text track: ${err instanceof Error ? err.message : String(err)}`);
        }
    }
}